version: "3.5"

services:

  label-studio:
    container_name: label-studio
    image: label-studio:latest
    build:
      context: "https://github.com/heartexlabs/label-studio.git"
    ports:
      - 8200:8200
    command: -i ${input_data} -l ${config} -c /data/config/config.json
    volumes:
      - "./storage/label-studio:/data"
    links:
      - model
    depends_on:
      - model

  redis:
    container_name: redis
    image: redis:alpine
    hostname: redis
    volumes:
      - "./storage/redis:/data"
    ports:
      - 6379:6379

  model:
    container_name: model
    environment:
      - RQ_QUEUE_NAME=model
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - pretrained_model=${pretrained_model:-bert-base-uncased}
      - cache_dir=/data/pretrained_model_cache
    image: model:latest
    build:
      context: .
    ports:
      - 9090:9090
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - "./storage/model:/data"
