version: "3.5"
services:
  label-studio:
    container_name: label-studio
    image: heartexlabs/label-studio:latest
    ports:
      - ${LABEL_STUDIO_PORT}:8200
    volumes:
      - ./storage/label-studio:/data
    command: |-
      ./scripts/wait-for-it.sh label-studio-ml-backend:9090 --
      label-studio start my_project -p 8200 --init --force
      -l /data/${APP}.xml
      --ml-backend-url http://label-studio-ml-backend:9090
      --ml-backend-name my_model
    links:
      - label-studio-ml-backend
    depends_on:
      - label-studio-ml-backend
  redis-local:
    container_name: redis-local
    image: redis:alpine
    hostname: redis
    volumes:
      - "./storage/redis-local:/data"
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
  label-studio-ml-backend:
    container_name: label-studio-ml-backend
    environment:
      - RQ_QUEUE_NAME=label-studio
      - REDIS_HOST=redis-local
      - REDIS_PORT=${REDIS_PORT}
      - WSGI_APP=wsgi_${APP}
      - pretrained_model=${pretrained_model:-bert-base-uncased}
      - model_dir=/data/model
      - cache_dir=/data/pretrained_model_cache
    image: label-studio-ml-backend:latest
    build:
      context: image_classifier
      shm_size: '32gb'
    ports:
      - ${ML_BACKEND_PORT}:9090
    depends_on:
      - redis-local
    links:
      - redis-local
    volumes:
      - "./storage/label-studio-ml-backend:/data"