version: "3.5"

services:

  label-studio:
    container_name: label-studio
    image: heartexlabs/label-studio:latest
    ports:
      - 8200:8200
    volumes:
      - "./storage/label-studio:/data"
    command: |-
      label-studio start my_project --init --force
      -l /data/labels.xml
      --root-dir /data
      --ml-backend-url http://model:9090
      --ml-backend-name model
    links:
      - model
    depends_on:
      - model

  redis:
    container_name: redis-local
    image: redis:alpine
    hostname: redis
    volumes:
      - "./storage/redis:/data"
    ports:
      - 6380:6380

  model:
    container_name: label-studio-ml-backend
    environment:
      - RQ_QUEUE_NAME=label-studio
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      - pretrained_model=${pretrained_model:-bert-base-uncased}
      - model_dir=/data/model
      - cache_dir=/data/pretrained_model_cache
    image: model:latest
    build:
      context: .
    ports:
      - 9090:9090
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - "./storage/model:/data"
